// BedWars kit dataset — compiled from the BedWars Fandom Wiki (Kit page + Class page)
// class: Fighter, Ranged, Tank, Support, Movement, Economy, Destroyer, Defender, Misc
// obtain: Free, Shop, BattlePass, PlayerLevel, Bundle

const KITS = [
  // Free (instant on join)
  { name: "Isabel", class: "Fighter", obtain: "Free" },
  { name: "Ragnar", class: "Destroyer", obtain: "Free" },
  { name: "Marcel", class: "Defender", obtain: "Free" },

  // Player Level milestones
  { name: "Whisper", class: "Support", obtain: "PlayerLevel", level: 10 },
  { name: "Taliyah", class: "Economy", obtain: "PlayerLevel", level: 15 },

  // Shop kits (399/10,000 or 479/12,000)
  { name: "Abaddon", class: "Fighter", obtain: "Shop" },
  { name: "Adetunde", class: "Fighter", obtain: "Shop" },
  { name: "Arachne", class: "Movement", obtain: "Shop" },
  { name: "Archer", class: "Ranged", obtain: "Shop" },
  { name: "Axolotl Amy", class: "Support", obtain: "Shop" },
  { name: "Baker", class: "Support", obtain: "Shop" },
  { name: "Barbarian", class: "Fighter", obtain: "Shop" },
  { name: "Builder", class: "Defender", obtain: "Shop" },
  { name: "Crypt", class: "Fighter", obtain: "Shop" },
  { name: "Cyber", class: "Economy", obtain: "Shop" },
  { name: "Death Adder", class: "Destroyer", obtain: "Shop" },
  { name: "Eldertree", class: "Tank", obtain: "Shop" },
  { name: "Eldric", class: "Fighter", obtain: "Shop" },
  { name: "Evelynn", class: "Fighter", obtain: "Shop" },
  { name: "Farmer Cletus", class: "Economy", obtain: "Shop" },
  { name: "Freiya", class: "Fighter", obtain: "Shop" },
  { name: "Grim Reaper", class: "Fighter", obtain: "Shop" },
  { name: "Grove", class: "Economy", obtain: "Shop" },
  { name: "Hannah", class: "Fighter", obtain: "Shop" },
  { name: "Infernal Shielder", class: "Tank", obtain: "Shop" },
  { name: "Kaida", class: "Fighter", obtain: "Shop" },
  { name: "Lassy", class: "Fighter", obtain: "Shop" },
  { name: "Lian", class: "Fighter", obtain: "Shop" },
  { name: "Lyla", class: "Ranged", obtain: "Shop" },
  { name: "Marina", class: "Defender", obtain: "Shop" },
  { name: "Marrow", class: "Misc", obtain: "Shop" },
  { name: "Martin", class: "Tank", obtain: "Shop" },
  { name: "Melody", class: "Support", obtain: "Shop" },
  { name: "Milo", class: "Economy", obtain: "Shop" },
  { name: "Miner", class: "Economy", obtain: "Shop" },
  { name: "Nahla", class: "Support", obtain: "Shop" },
  { name: "Nazar", class: "Fighter", obtain: "Shop" },
  { name: "Pirate Davey", class: "Destroyer", obtain: "Shop" },
  { name: "Ramil", class: "Fighter", obtain: "Shop" },
  { name: "Silas", class: "Support", obtain: "Shop" },
  { name: "Skoll", class: "Fighter", obtain: "Shop" },
  { name: "Trinity", class: "Support", obtain: "Shop" },
  { name: "Triton", class: "Movement", obtain: "Shop" },
  { name: "Trixie", class: "Fighter", obtain: "Shop" },
  { name: "Uma", class: "Ranged", obtain: "Shop" },
  { name: "Vanessa", class: "Ranged", obtain: "Shop" },
  { name: "Void Knight", class: "Fighter", obtain: "Shop" },
  { name: "Vulcan", class: "Defender", obtain: "Shop" },
  { name: "Wren", class: "Economy", obtain: "Shop" },
  { name: "Yuzi", class: "Movement", obtain: "Shop" },
  { name: "Zarrah", class: "Fighter", obtain: "Shop" },
  { name: "Zenith", class: "Economy", obtain: "Shop" },
  { name: "Zeno", class: "Ranged", obtain: "Shop" },

  // Bundle-exclusive kits (holiday / lunar / event bundles, not in general shop)
  { name: "Void Regent", class: "Movement", obtain: "Bundle" },
  { name: "Sheila", class: "Fighter", obtain: "Bundle" },
  { name: "Sigrid", class: "Movement", obtain: "Bundle" },
  { name: "Krystal", class: "Movement", obtain: "Bundle" },
  { name: "Sophia", class: "Misc", obtain: "Bundle" },
  { name: "Ember", class: "Fighter", obtain: "Bundle" },
  { name: "Lumen", class: "Fighter", obtain: "Bundle" },

  // Battle Pass kits (various seasons)
  { name: "Warrior", class: "Tank", obtain: "BattlePass", season: 1 },
  { name: "Bounty Hunter", class: "Economy", obtain: "BattlePass", season: 1 },
  { name: "Beekeeper Beatrix", class: "Economy", obtain: "BattlePass", season: 1 },
  { name: "Jade", class: "Movement", obtain: "BattlePass", season: 1 },
  { name: "Raven", class: "Ranged", obtain: "BattlePass", season: 1 },
  { name: "Spirit Catcher", class: "Ranged", obtain: "BattlePass", season: 1 },
  { name: "Pyro", class: "Fighter", obtain: "BattlePass", season: 1 },
  { name: "Trapper", class: "Defender", obtain: "BattlePass", season: 2 },
  { name: "Gompy", class: "Ranged", obtain: "BattlePass", season: 2 },
  { name: "Fisherman", class: "Economy", obtain: "BattlePass", season: 2 },
  { name: "Jack", class: "Ranged", obtain: "BattlePass", season: 2 },
  { name: "Ares", class: "Ranged", obtain: "BattlePass", season: 2 },
  { name: "Santa", class: "Destroyer", obtain: "BattlePass", season: 3 },
  { name: "Gingerbread Man", class: "Support", obtain: "BattlePass", season: 3 },
  { name: "Smoke", class: "Destroyer", obtain: "BattlePass", season: 3 },
  { name: "Yeti", class: "Destroyer", obtain: "BattlePass", season: 3 },
  { name: "Frosty", class: "Ranged", obtain: "BattlePass", season: 3 },
  { name: "Aery", class: "Fighter", obtain: "BattlePass", season: 3 },
  { name: "Metal Detector", class: "Economy", obtain: "BattlePass", season: 4 },
  { name: "Alchemist", class: "Support", obtain: "BattlePass", season: 4 },
  { name: "Sheep Herder", class: "Fighter", obtain: "BattlePass", season: 4 },
  { name: "Crocowolf", class: "Fighter", obtain: "BattlePass", season: 4 },
  { name: "Conqueror", class: "Support", obtain: "BattlePass", season: 4 },
  { name: "Nyx", class: "Fighter", obtain: "BattlePass", season: 4 },
  { name: "Lucía", class: "Economy", obtain: "BattlePass", season: 5 },
  { name: "Merchant Marco", class: "Economy", obtain: "BattlePass", season: 5 },
  { name: "Dino Tamer Dom", class: "Destroyer", obtain: "BattlePass", season: 5 },
  { name: "Cobalt", class: "Tank", obtain: "BattlePass", season: 5 },
  { name: "Star Collector Stella", class: "Support", obtain: "BattlePass", season: 5 },
  { name: "Zephyr", class: "Movement", obtain: "BattlePass", season: 5 },
  { name: "Lani", class: "Support", obtain: "BattlePass", season: 6 },
  { name: "Whim", class: "Fighter", obtain: "BattlePass", season: 6 },
  { name: "Xu'rot", class: "Fighter", obtain: "BattlePass", season: 6 },
  { name: "Warden", class: "Destroyer", obtain: "BattlePass", season: 6 },
  { name: "Kaliyah", class: "Fighter", obtain: "BattlePass", season: 6 },
  { name: "Drill", class: "Economy", obtain: "BattlePass", season: 7 },
  { name: "Flora", class: "Movement", obtain: "BattlePass", season: 7 },
  { name: "Umbra", class: "Support", obtain: "BattlePass", season: 7 },
  { name: "Caitlyn", class: "Fighter", obtain: "BattlePass", season: 7 },
  { name: "Ignis", class: "Support", obtain: "BattlePass", season: 8 },
  { name: "Fortuna", class: "Fighter", obtain: "BattlePass", season: 8 },
  { name: "Elektra", class: "Movement", obtain: "BattlePass", season: 8 },
  { name: "Umeko", class: "Ranged", obtain: "BattlePass", season: 9 },
  { name: "Yamini", class: "Movement", obtain: "BattlePass", season: 9 },
  { name: "Cogsworth", class: "Economy", obtain: "BattlePass", season: 9 },
  { name: "Noelle", class: "Support", obtain: "BattlePass", season: 9 },
  { name: "Terra", class: "Fighter", obtain: "BattlePass", season: 9 },
  { name: "Agni", class: "Fighter", obtain: "BattlePass", season: 10 },
  { name: "Styx", class: "Movement", obtain: "BattlePass", season: 10 },
  { name: "Nyoka", class: "Support", obtain: "BattlePass", season: 10 },
  { name: "Bekzat", class: "Ranged", obtain: "BattlePass", season: 10 },
  { name: "Hephaestus", class: "Tank", obtain: "BattlePass", season: 10 },
  { name: "Zola", class: "Support", obtain: "BattlePass", season: 11 },
];

// derive extra guessable attributes
KITS.forEach(k => {
  const clean = k.name.replace(/[^A-Za-z]/g, "");
  k.firstLetter = clean[0].toUpperCase();
  k.length = clean.length;
  k.words = k.name.trim().split(/\s+/).length;
});

if (typeof module !== "undefined") module.exports = KITS;
